#!/bin/bash
# I want to make sure that the directory is clean and has nothing left over from
# previous deployments. The servers auto scale so the directory may or may not
# exist...
if [ -f /var/www/html/index.html ]
then
rm -f /var/www/html/index.html
else
echo "File does not exist, proceeding..."
fi
apt-get install -y apache2
apt-get install -y npm
apt-get install -y python-pip
apt-get install -y yarn

